<?php

namespace Azimuth\PagesBundle\Repository;

/**
 * PdfsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfsRepository extends \Doctrine\ORM\EntityRepository
{
}
