<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * CandidatOffreEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatOffreEmploiRepository extends \Doctrine\ORM\EntityRepository
{
}
