<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneByUser($userId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.utilisateur.id =:userId')
            ->orderBy('c.id')
            ->setParameter('userId', $userId);
        return $qb->getQuery()->getResult();
    }
}
