<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * ConnaissancesInformatiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnaissancesInformatiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
