<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * ConnaissancesLinguistiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnaissancesLinguistiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
