<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * EquiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquiteRepository extends \Doctrine\ORM\EntityRepository
{
}
