<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * NiveauLinguistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauLinguistiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
