<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * NiveauScolariteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauScolariteRepository extends \Doctrine\ORM\EntityRepository
{
}
