<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * OffreEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploiRepository extends \Doctrine\ORM\EntityRepository
{

    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.offreEmploiTitre like :chaine')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }


}
