<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * TypeEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEmploiRepository extends \Doctrine\ORM\EntityRepository
{
}
