<?php

namespace Azimuth\UtilisateursBundle\Repository;

/**
 * Utilisateur_rolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateur_rolesRepository extends \Doctrine\ORM\EntityRepository
{
}
