<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * ConnaissanceLinguistiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnaissanceLinguistiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
