<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * CvCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
