<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * FilestoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilestoreRepository extends \Doctrine\ORM\EntityRepository
{
}
