<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * LettreMotivationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettreMotivationRepository extends \Doctrine\ORM\EntityRepository
{
}
