<?php

namespace Azimuth\AzimuthBundle\Repository;

/**
 * RecruteurCvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruteurCvRepository extends \Doctrine\ORM\EntityRepository
{
}
