# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


    Azimuth\AzimuthBundle\Service\FileUploader:
        arguments:
           $targetDir: '%brochures_directory%'

    _defaults:
        # ... be sure autowiring is enabled
        autowire: true
    # ...

    Azimuth\AzimuthBundle\EventListener\BrochureUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
